In [2]:
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pad_sequence
from sklearn.model_selection import KFold
import polars as pl
import os
from typing import Optional

## General Testing

In [82]:
class LSTMClassifier(nn.Module):
    def __init__(self, input_size, hidden_dim_1, num_layers, output_size, hidden_dim_2: int = 32, dropout_rate: float = 0.3):
        super(LSTMClassifier, self).__init__()
        self.hidden_dim_1 = hidden_dim_1
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size,
                            self.hidden_dim_1,
                            num_layers=num_layers,
                            batch_first=True
                           )
        #self.dropout_1 = nn.Dropout(dropout_rate)
        self.fc1 = nn.Linear(self.hidden_dim_1, hidden_dim_2)
        self.relu = nn.ReLU()
        #self.dropout_2 = nn.Dropout(dropout_rate)
        self.fc2 = nn.Linear(hidden_dim_2, output_size)
        #self.batch_size = 1
    
    def forward(self, x: torch.Tensor):
        h = torch.zeros(self.num_layers, x.size(0), self.hidden_dim_1).to(x.device)
        c = torch.zeros(self.num_layers, x.size(0), self.hidden_dim_1).to(x.device)
        # h = torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).to(x.device)
        # c = torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).to(x.device)
        out, _ = self.lstm(x, (h, c))
        out = out[:, -1, :]
        #out = self.dropout_1(out)
        out = self.fc1(out)
        out = self.relu(out)
        #out = self.dropout_2(out)
        out = self.fc2(out)
        return out

In [4]:
# Generate sample data
X_train = torch.rand(100, 10, 50)  # 100 sequences of length 10 with 50 features each
y_train = torch.randint(3, size=(100,))  # Binary labels (0 or 1)

print(X_train.shape)
y_train

torch.Size([100, 10, 50])

tensor([1, 1, 1, 0, 1, 1, 2, 0, 2, 1, 2, 0, 0, 2, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0,
        1, 2, 2, 2, 2, 1, 1, 0, 0, 1, 0, 2, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 2, 0,
        1, 0, 1, 2, 2, 2, 1, 2, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2, 2,
        1, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2,
        2, 0, 1, 0])

In [5]:
y_train.unique(return_counts=True)

(tensor([0, 1, 2]), tensor([30, 32, 38]))

In [6]:
batch_size = 1
batches_X = X_train.split(batch_size)
batches_y = y_train.split(batch_size)
print(batches_X[-1].shape)
batches_y[-1].shape

torch.Size([1, 10, 50])

torch.Size([1])

In [57]:
input_size = 50
hidden_size = 64
num_layers = 1
output_size = 3

model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
model

LSTMClassifier(
  (lstm): LSTM(50, 64, batch_first=True)
  (dropout_1): Dropout(p=0.3, inplace=False)
  (fc1): Linear(in_features=64, out_features=32, bias=True)
  (dropout_2): Dropout(p=0.3, inplace=False)
  (fc2): Linear(in_features=32, out_features=3, bias=True)
)

In [58]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

num_epochs = 10
for epoch in range(num_epochs):
    for bind in range(len(batches_X)):
        batch_X = batches_X[bind]
        batch_y = batches_y[bind]
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        print(f'Epoch [{epoch+1}/{num_epochs}], Batch [{bind}/{len(batches_X)}], Loss: {loss.item()}')

Epoch [1/10], Batch [0/100], Loss: 1.0710283517837524
Epoch [1/10], Batch [1/100], Loss: 0.6671250462532043
Epoch [1/10], Batch [2/100], Loss: 0.3299598693847656
Epoch [1/10], Batch [3/100], Loss: 3.0616395473480225
Epoch [1/10], Batch [4/100], Loss: 0.14825040102005005
Epoch [1/10], Batch [5/100], Loss: 0.10798610746860504
Epoch [1/10], Batch [6/100], Loss: 4.8511528968811035
Epoch [1/10], Batch [7/100], Loss: 3.326906442642212
Epoch [1/10], Batch [8/100], Loss: 2.2599830627441406
Epoch [1/10], Batch [9/100], Loss: 0.4860837459564209
Epoch [1/10], Batch [10/100], Loss: 2.3978488445281982
Epoch [1/10], Batch [11/100], Loss: 1.178433895111084
Epoch [1/10], Batch [12/100], Loss: 1.0268296003341675
Epoch [1/10], Batch [13/100], Loss: 1.4037244319915771
Epoch [1/10], Batch [14/100], Loss: 1.2232884168624878
Epoch [1/10], Batch [15/100], Loss: 1.2940211296081543
Epoch [1/10], Batch [16/100], Loss: 1.0889898538589478
Epoch [1/10], Batch [17/100], Loss: 1.0496946573257446
Epoch [1/10], Batch [18/100], Loss: 0.9336752891540527
Epoch [1/10], Batch [19/100], Loss: 0.9501476883888245
Epoch [1/10], Batch [20/100], Loss: 1.1772301197052002
Epoch [1/10], Batch [21/100], Loss: 0.8731895685195923
Epoch [1/10], Batch [22/100], Loss: 1.2015554904937744
Epoch [1/10], Batch [23/100], Loss: 1.3900299072265625
Epoch [1/10], Batch [24/100], Loss: 1.3586044311523438
Epoch [1/10], Batch [25/100], Loss: 0.8677037358283997
Epoch [1/10], Batch [26/100], Loss: 1.0888783931732178
Epoch [1/10], Batch [27/100], Loss: 0.9898114204406738
Epoch [1/10], Batch [28/100], Loss: 0.9442915320396423
Epoch [1/10], Batch [29/100], Loss: 1.2698783874511719
Epoch [1/10], Batch [30/100], Loss: 1.6062825918197632
Epoch [1/10], Batch [31/100], Loss: 1.439429759979248
Epoch [1/10], Batch [32/100], Loss: 1.4448901414871216
Epoch [1/10], Batch [33/100], Loss: 1.1472411155700684
Epoch [1/10], Batch [34/100], Loss: 1.402632713317871
Epoch [1/10], Batch [35/100], Loss: 0.9059200286865234
Epoch [1/10], Batch [36/100], Loss: 1.0613237619400024
Epoch [1/10], Batch [37/100], Loss: 1.2224804162979126
Epoch [1/10], Batch [38/100], Loss: 1.0842022895812988
Epoch [1/10], Batch [39/100], Loss: 0.8589281439781189
Epoch [1/10], Batch [40/100], Loss: 0.9818322062492371
Epoch [1/10], Batch [41/100], Loss: 1.108270287513733
Epoch [1/10], Batch [42/100], Loss: 1.0007127523422241
Epoch [1/10], Batch [43/100], Loss: 1.0731083154678345
Epoch [1/10], Batch [44/100], Loss: 1.1236176490783691
Epoch [1/10], Batch [45/100], Loss: 1.2371195554733276
Epoch [1/10], Batch [46/100], Loss: 1.0279966592788696
Epoch [1/10], Batch [47/100], Loss: 1.2339471578598022
Epoch [1/10], Batch [48/100], Loss: 0.9641722440719604
Epoch [1/10], Batch [49/100], Loss: 0.978538990020752
Epoch [1/10], Batch [50/100], Loss: 1.2185319662094116
Epoch [1/10], Batch [51/100], Loss: 1.2303845882415771
Epoch [1/10], Batch [52/100], Loss: 1.4371180534362793
Epoch [1/10], Batch [53/100], Loss: 1.2298604249954224
Epoch [1/10], Batch [54/100], Loss: 1.016926646232605
Epoch [1/10], Batch [55/100], Loss: 1.1459561586380005
Epoch [1/10], Batch [56/100], Loss: 1.2762813568115234
Epoch [1/10], Batch [57/100], Loss: 0.752439558506012
Epoch [1/10], Batch [58/100], Loss: 0.8615977764129639
Epoch [1/10], Batch [59/100], Loss: 1.4009414911270142
Epoch [1/10], Batch [60/100], Loss: 1.0362894535064697
Epoch [1/10], Batch [61/100], Loss: 1.2301337718963623
Epoch [1/10], Batch [62/100], Loss: 1.152240514755249
Epoch [1/10], Batch [63/100], Loss: 0.9929419159889221
Epoch [1/10], Batch [64/100], Loss: 1.6975629329681396
Epoch [1/10], Batch [65/100], Loss: 1.3259981870651245
Epoch [1/10], Batch [66/100], Loss: 1.4085744619369507
Epoch [1/10], Batch [67/100], Loss: 1.0936449766159058
Epoch [1/10], Batch [68/100], Loss: 1.0917510986328125
Epoch [1/10], Batch [69/100], Loss: 1.0924100875854492
Epoch [1/10], Batch [70/100], Loss: 0.9174953699111938
Epoch [1/10], Batch [71/100], Loss: 0.9177495241165161
Epoch [1/10], Batch [72/100], Loss: 1.1394412517547607
Epoch [1/10], Batch [73/100], Loss: 1.1868699789047241
Epoch [1/10], Batch [74/100], Loss: 1.1678184270858765
Epoch [1/10], Batch [75/100], Loss: 1.1354998350143433
Epoch [1/10], Batch [76/100], Loss: 0.6935790777206421
Epoch [1/10], Batch [77/100], Loss: 0.8411598205566406
Epoch [1/10], Batch [78/100], Loss: 0.8987725377082825
Epoch [1/10], Batch [79/100], Loss: 1.0395479202270508
Epoch [1/10], Batch [80/100], Loss: 1.6733269691467285
Epoch [1/10], Batch [81/100], Loss: 1.893568515777588
Epoch [1/10], Batch [82/100], Loss: 1.0114011764526367
Epoch [1/10], Batch [83/100], Loss: 0.7981225252151489
Epoch [1/10], Batch [84/100], Loss: 0.7322424650192261
Epoch [1/10], Batch [85/100], Loss: 1.620714783668518
Epoch [1/10], Batch [86/100], Loss: 0.7263883948326111
Epoch [1/10], Batch [87/100], Loss: 0.7228339314460754
Epoch [1/10], Batch [88/100], Loss: 0.8822486996650696
Epoch [1/10], Batch [89/100], Loss: 1.3135426044464111
Epoch [1/10], Batch [90/100], Loss: 1.3672090768814087
Epoch [1/10], Batch [91/100], Loss: 1.2641117572784424
Epoch [1/10], Batch [92/100], Loss: 1.2064094543457031
Epoch [1/10], Batch [93/100], Loss: 0.8210644721984863
Epoch [1/10], Batch [94/100], Loss: 0.6578122973442078
Epoch [1/10], Batch [95/100], Loss: 0.8043813705444336
Epoch [1/10], Batch [96/100], Loss: 0.6844773292541504
Epoch [1/10], Batch [97/100], Loss: 1.2162941694259644
Epoch [1/10], Batch [98/100], Loss: 1.6717345714569092
Epoch [1/10], Batch [99/100], Loss: 1.372083067893982
Epoch [2/10], Batch [0/100], Loss: 1.4040563106536865
Epoch [2/10], Batch [1/100], Loss: 1.0632401704788208
Epoch [2/10], Batch [2/100], Loss: 1.500087022781372
Epoch [2/10], Batch [3/100], Loss: 1.419325351715088
Epoch [2/10], Batch [4/100], Loss: 1.4565114974975586
Epoch [2/10], Batch [5/100], Loss: 1.3540024757385254
Epoch [2/10], Batch [6/100], Loss: 1.0097994804382324
Epoch [2/10], Batch [7/100], Loss: 1.334193468093872
Epoch [2/10], Batch [8/100], Loss: 1.0440205335617065
Epoch [2/10], Batch [9/100], Loss: 1.1009411811828613
Epoch [2/10], Batch [10/100], Loss: 0.9726764559745789
Epoch [2/10], Batch [11/100], Loss: 1.142876386642456
Epoch [2/10], Batch [12/100], Loss: 1.3847870826721191
Epoch [2/10], Batch [13/100], Loss: 1.145308256149292
Epoch [2/10], Batch [14/100], Loss: 0.9073088765144348
Epoch [2/10], Batch [15/100], Loss: 1.07158362865448
Epoch [2/10], Batch [16/100], Loss: 0.7478712797164917
Epoch [2/10], Batch [17/100], Loss: 1.3386390209197998
Epoch [2/10], Batch [18/100], Loss: 1.1423180103302002
Epoch [2/10], Batch [19/100], Loss: 1.3048580884933472
Epoch [2/10], Batch [20/100], Loss: 0.8989036679267883
Epoch [2/10], Batch [21/100], Loss: 1.1289914846420288
Epoch [2/10], Batch [22/100], Loss: 1.3488295078277588
Epoch [2/10], Batch [23/100], Loss: 1.2077521085739136
Epoch [2/10], Batch [24/100], Loss: 0.7540098428726196
Epoch [2/10], Batch [25/100], Loss: 1.1532258987426758
Epoch [2/10], Batch [26/100], Loss: 1.0418778657913208
Epoch [2/10], Batch [27/100], Loss: 1.1170085668563843
Epoch [2/10], Batch [28/100], Loss: 1.015058159828186
Epoch [2/10], Batch [29/100], Loss: 0.8021989464759827
Epoch [2/10], Batch [30/100], Loss: 0.8601083159446716
Epoch [2/10], Batch [31/100], Loss: 1.6535788774490356
Epoch [2/10], Batch [32/100], Loss: 1.38246750831604
Epoch [2/10], Batch [33/100], Loss: 0.8085096478462219
Epoch [2/10], Batch [34/100], Loss: 1.5346351861953735
Epoch [2/10], Batch [35/100], Loss: 1.120936393737793
Epoch [2/10], Batch [36/100], Loss: 1.2722091674804688
Epoch [2/10], Batch [37/100], Loss: 1.2192082405090332
Epoch [2/10], Batch [38/100], Loss: 1.0859835147857666
Epoch [2/10], Batch [39/100], Loss: 1.1000951528549194
Epoch [2/10], Batch [40/100], Loss: 1.2591288089752197
Epoch [2/10], Batch [41/100], Loss: 1.1223249435424805
Epoch [2/10], Batch [42/100], Loss: 1.1373529434204102
Epoch [2/10], Batch [43/100], Loss: 1.1414916515350342
Epoch [2/10], Batch [44/100], Loss: 1.1233469247817993
Epoch [2/10], Batch [45/100], Loss: 1.062706708908081
Epoch [2/10], Batch [46/100], Loss: 1.0621981620788574
Epoch [2/10], Batch [47/100], Loss: 0.9860123991966248
Epoch [2/10], Batch [48/100], Loss: 1.121460199356079
Epoch [2/10], Batch [49/100], Loss: 1.0434319972991943
Epoch [2/10], Batch [50/100], Loss: 1.2109622955322266
Epoch [2/10], Batch [51/100], Loss: 1.1191154718399048
Epoch [2/10], Batch [52/100], Loss: 1.175675630569458
Epoch [2/10], Batch [53/100], Loss: 1.1765307188034058
Epoch [2/10], Batch [54/100], Loss: 1.1781933307647705
Epoch [2/10], Batch [55/100], Loss: 1.1416034698486328
Epoch [2/10], Batch [56/100], Loss: 1.1051089763641357
Epoch [2/10], Batch [57/100], Loss: 1.0244253873825073
Epoch [2/10], Batch [58/100], Loss: 1.1439169645309448
Epoch [2/10], Batch [59/100], Loss: 1.037723422050476
Epoch [2/10], Batch [60/100], Loss: 1.201465368270874
Epoch [2/10], Batch [61/100], Loss: 1.1129870414733887
Epoch [2/10], Batch [62/100], Loss: 1.1460744142532349
Epoch [2/10], Batch [63/100], Loss: 1.1714450120925903
Epoch [2/10], Batch [64/100], Loss: 1.1704320907592773
Epoch [2/10], Batch [65/100], Loss: 1.1485624313354492
Epoch [2/10], Batch [66/100], Loss: 1.0126806497573853
Epoch [2/10], Batch [67/100], Loss: 1.1267229318618774
Epoch [2/10], Batch [68/100], Loss: 1.0555235147476196
Epoch [2/10], Batch [69/100], Loss: 1.079312801361084
Epoch [2/10], Batch [70/100], Loss: 1.1219209432601929
Epoch [2/10], Batch [71/100], Loss: 1.119119644165039
Epoch [2/10], Batch [72/100], Loss: 1.231663465499878
Epoch [2/10], Batch [73/100], Loss: 1.1113392114639282
Epoch [2/10], Batch [74/100], Loss: 1.0386877059936523
Epoch [2/10], Batch [75/100], Loss: 1.0794169902801514
Epoch [2/10], Batch [76/100], Loss: 1.0393260717391968
Epoch [2/10], Batch [77/100], Loss: 1.0750731229782104
Epoch [2/10], Batch [78/100], Loss: 1.0908578634262085
Epoch [2/10], Batch [79/100], Loss: 1.0128074884414673
Epoch [2/10], Batch [80/100], Loss: 1.1638808250427246
Epoch [2/10], Batch [81/100], Loss: 1.2539443969726562
Epoch [2/10], Batch [82/100], Loss: 0.9485043883323669
Epoch [2/10], Batch [83/100], Loss: 1.0359832048416138
Epoch [2/10], Batch [84/100], Loss: 1.0246655941009521
Epoch [2/10], Batch [85/100], Loss: 1.1870574951171875
Epoch [2/10], Batch [86/100], Loss: 1.068079948425293
Epoch [2/10], Batch [87/100], Loss: 0.9608761668205261
Epoch [2/10], Batch [88/100], Loss: 1.0048547983169556
Epoch [2/10], Batch [89/100], Loss: 1.3639447689056396
Epoch [2/10], Batch [90/100], Loss: 1.3948094844818115
Epoch [2/10], Batch [91/100], Loss: 1.2849454879760742
Epoch [2/10], Batch [92/100], Loss: 1.0487736463546753
Epoch [2/10], Batch [93/100], Loss: 0.95661461353302
Epoch [2/10], Batch [94/100], Loss: 0.960515558719635
Epoch [2/10], Batch [95/100], Loss: 0.8664572238922119
Epoch [2/10], Batch [96/100], Loss: 0.9044548869132996
Epoch [2/10], Batch [97/100], Loss: 1.2332850694656372
Epoch [2/10], Batch [98/100], Loss: 1.332269310951233
Epoch [2/10], Batch [99/100], Loss: 1.222037672996521
Epoch [3/10], Batch [0/100], Loss: 1.2645492553710938
Epoch [3/10], Batch [1/100], Loss: 1.2719666957855225
Epoch [3/10], Batch [2/100], Loss: 1.20889413356781
Epoch [3/10], Batch [3/100], Loss: 1.1416654586791992
Epoch [3/10], Batch [4/100], Loss: 1.2251009941101074
Epoch [3/10], Batch [5/100], Loss: 1.1825937032699585
Epoch [3/10], Batch [6/100], Loss: 0.9464825987815857
Epoch [3/10], Batch [7/100], Loss: 1.4032986164093018
Epoch [3/10], Batch [8/100], Loss: 0.9202205538749695
Epoch [3/10], Batch [9/100], Loss: 1.0199389457702637
Epoch [3/10], Batch [10/100], Loss: 0.9900999665260315
Epoch [3/10], Batch [11/100], Loss: 1.242208480834961
Epoch [3/10], Batch [12/100], Loss: 1.2799439430236816
Epoch [3/10], Batch [13/100], Loss: 0.93583083152771
Epoch [3/10], Batch [14/100], Loss: 1.006961703300476
Epoch [3/10], Batch [15/100], Loss: 1.0238741636276245
Epoch [3/10], Batch [16/100], Loss: 1.0750712156295776
Epoch [3/10], Batch [17/100], Loss: 1.3878543376922607
Epoch [3/10], Batch [18/100], Loss: 0.997486412525177
Epoch [3/10], Batch [19/100], Loss: 0.9765991568565369
Epoch [3/10], Batch [20/100], Loss: 1.1084364652633667
Epoch [3/10], Batch [21/100], Loss: 0.9657689332962036
Epoch [3/10], Batch [22/100], Loss: 1.3388957977294922
Epoch [3/10], Batch [23/100], Loss: 1.4140865802764893
Epoch [3/10], Batch [24/100], Loss: 0.959945023059845
Epoch [3/10], Batch [25/100], Loss: 1.0469967126846313
Epoch [3/10], Batch [26/100], Loss: 1.0196787118911743
Epoch [3/10], Batch [27/100], Loss: 1.0301119089126587
Epoch [3/10], Batch [28/100], Loss: 1.0635586977005005
Epoch [3/10], Batch [29/100], Loss: 0.9860544800758362
Epoch [3/10], Batch [30/100], Loss: 1.004475712776184
Epoch [3/10], Batch [31/100], Loss: 1.1898916959762573
Epoch [3/10], Batch [32/100], Loss: 1.2591685056686401
Epoch [3/10], Batch [33/100], Loss: 0.9641904234886169
Epoch [3/10], Batch [34/100], Loss: 1.2298688888549805
Epoch [3/10], Batch [35/100], Loss: 0.9955422878265381
Epoch [3/10], Batch [36/100], Loss: 1.325376272201538
Epoch [3/10], Batch [37/100], Loss: 1.2776482105255127
Epoch [3/10], Batch [38/100], Loss: 0.98115473985672
Epoch [3/10], Batch [39/100], Loss: 1.0840452909469604
Epoch [3/10], Batch [40/100], Loss: 1.1678968667984009
Epoch [3/10], Batch [41/100], Loss: 1.027927041053772
Epoch [3/10], Batch [42/100], Loss: 1.2400208711624146
Epoch [3/10], Batch [43/100], Loss: 0.9292415380477905
Epoch [3/10], Batch [44/100], Loss: 1.08412766456604
Epoch [3/10], Batch [45/100], Loss: 0.9558033347129822
Epoch [3/10], Batch [46/100], Loss: 1.0907975435256958
Epoch [3/10], Batch [47/100], Loss: 1.1884946823120117
Epoch [3/10], Batch [48/100], Loss: 1.098549723625183
Epoch [3/10], Batch [49/100], Loss: 1.1653863191604614
Epoch [3/10], Batch [50/100], Loss: 1.0526982545852661
Epoch [3/10], Batch [51/100], Loss: 1.071132779121399
Epoch [3/10], Batch [52/100], Loss: 1.175148844718933
Epoch [3/10], Batch [53/100], Loss: 1.1291630268096924
Epoch [3/10], Batch [54/100], Loss: 1.1438051462173462
Epoch [3/10], Batch [55/100], Loss: 1.1430058479309082
Epoch [3/10], Batch [56/100], Loss: 1.1445403099060059
Epoch [3/10], Batch [57/100], Loss: 1.019679069519043
Epoch [3/10], Batch [58/100], Loss: 1.0691851377487183
Epoch [3/10], Batch [59/100], Loss: 1.1436821222305298
Epoch [3/10], Batch [60/100], Loss: 1.0263347625732422
Epoch [3/10], Batch [61/100], Loss: 1.092262625694275
Epoch [3/10], Batch [62/100], Loss: 1.0704890489578247
Epoch [3/10], Batch [63/100], Loss: 1.224247932434082
Epoch [3/10], Batch [64/100], Loss: 1.1921205520629883
Epoch [3/10], Batch [65/100], Loss: 1.180420994758606
Epoch [3/10], Batch [66/100], Loss: 1.0842106342315674
Epoch [3/10], Batch [67/100], Loss: 1.0493956804275513
Epoch [3/10], Batch [68/100], Loss: 1.2294270992279053
Epoch [3/10], Batch [69/100], Loss: 1.1065711975097656
Epoch [3/10], Batch [70/100], Loss: 1.0628374814987183
Epoch [3/10], Batch [71/100], Loss: 1.0900036096572876
Epoch [3/10], Batch [72/100], Loss: 1.1753606796264648
Epoch [3/10], Batch [73/100], Loss: 1.0961202383041382
Epoch [3/10], Batch [74/100], Loss: 1.1381115913391113
Epoch [3/10], Batch [75/100], Loss: 1.0013984441757202
Epoch [3/10], Batch [76/100], Loss: 0.9766429662704468
Epoch [3/10], Batch [77/100], Loss: 1.0142465829849243
Epoch [3/10], Batch [78/100], Loss: 1.01212477684021
Epoch [3/10], Batch [79/100], Loss: 1.0333338975906372
Epoch [3/10], Batch [80/100], Loss: 1.2495172023773193
Epoch [3/10], Batch [81/100], Loss: 1.2153315544128418
Epoch [3/10], Batch [82/100], Loss: 1.0234345197677612
Epoch [3/10], Batch [83/100], Loss: 0.90757155418396
Epoch [3/10], Batch [84/100], Loss: 0.9144306778907776
Epoch [3/10], Batch [85/100], Loss: 1.3196370601654053
Epoch [3/10], Batch [86/100], Loss: 0.922048032283783
Epoch [3/10], Batch [87/100], Loss: 0.8529335856437683
Epoch [3/10], Batch [88/100], Loss: 0.8656576871871948
Epoch [3/10], Batch [89/100], Loss: 1.3138935565948486
Epoch [3/10], Batch [90/100], Loss: 1.338305115699768
Epoch [3/10], Batch [91/100], Loss: 1.3936363458633423
Epoch [3/10], Batch [92/100], Loss: 1.218869924545288
Epoch [3/10], Batch [93/100], Loss: 0.9509674906730652
Epoch [3/10], Batch [94/100], Loss: 0.8305765390396118
Epoch [3/10], Batch [95/100], Loss: 1.0190064907073975
Epoch [3/10], Batch [96/100], Loss: 0.7257342338562012
Epoch [3/10], Batch [97/100], Loss: 1.1998813152313232
Epoch [3/10], Batch [98/100], Loss: 1.2452009916305542
Epoch [3/10], Batch [99/100], Loss: 1.1423819065093994
Epoch [4/10], Batch [0/100], Loss: 1.429342269897461
Epoch [4/10], Batch [1/100], Loss: 1.1960676908493042
Epoch [4/10], Batch [2/100], Loss: 1.284447193145752
Epoch [4/10], Batch [3/100], Loss: 1.4215198755264282
Epoch [4/10], Batch [4/100], Loss: 1.242962121963501
Epoch [4/10], Batch [5/100], Loss: 1.256625771522522
Epoch [4/10], Batch [6/100], Loss: 0.9242700338363647
Epoch [4/10], Batch [7/100], Loss: 1.327605962753296
Epoch [4/10], Batch [8/100], Loss: 0.8842129707336426
Epoch [4/10], Batch [9/100], Loss: 1.057708501815796
Epoch [4/10], Batch [10/100], Loss: 0.9027667045593262
Epoch [4/10], Batch [11/100], Loss: 1.3787410259246826
Epoch [4/10], Batch [12/100], Loss: 1.3094351291656494
Epoch [4/10], Batch [13/100], Loss: 0.9873360395431519
Epoch [4/10], Batch [14/100], Loss: 1.1647677421569824
Epoch [4/10], Batch [15/100], Loss: 1.1588668823242188
Epoch [4/10], Batch [16/100], Loss: 1.1021581888198853
Epoch [4/10], Batch [17/100], Loss: 1.1783740520477295
Epoch [4/10], Batch [18/100], Loss: 0.972368597984314
Epoch [4/10], Batch [19/100], Loss: 0.9968666434288025
Epoch [4/10], Batch [20/100], Loss: 1.0906548500061035
Epoch [4/10], Batch [21/100], Loss: 1.0022556781768799
Epoch [4/10], Batch [22/100], Loss: 1.1988836526870728
Epoch [4/10], Batch [23/100], Loss: 1.2236504554748535
Epoch [4/10], Batch [24/100], Loss: 1.0942589044570923
Epoch [4/10], Batch [25/100], Loss: 1.0095542669296265
Epoch [4/10], Batch [26/100], Loss: 0.991934597492218
Epoch [4/10], Batch [27/100], Loss: 1.0050833225250244
Epoch [4/10], Batch [28/100], Loss: 1.0179312229156494
Epoch [4/10], Batch [29/100], Loss: 1.1526517868041992
Epoch [4/10], Batch [30/100], Loss: 1.0437839031219482
Epoch [4/10], Batch [31/100], Loss: 1.1770002841949463
Epoch [4/10], Batch [32/100], Loss: 1.1720513105392456
Epoch [4/10], Batch [33/100], Loss: 1.1011916399002075
Epoch [4/10], Batch [34/100], Loss: 1.2216627597808838
Epoch [4/10], Batch [35/100], Loss: 1.031116008758545
Epoch [4/10], Batch [36/100], Loss: 1.221501350402832
Epoch [4/10], Batch [37/100], Loss: 1.2853493690490723
Epoch [4/10], Batch [38/100], Loss: 0.9851468801498413
Epoch [4/10], Batch [39/100], Loss: 1.0543437004089355
Epoch [4/10], Batch [40/100], Loss: 1.0877878665924072
Epoch [4/10], Batch [41/100], Loss: 1.0282658338546753
Epoch [4/10], Batch [42/100], Loss: 1.1475119590759277
Epoch [4/10], Batch [43/100], Loss: 1.1555118560791016
Epoch [4/10], Batch [44/100], Loss: 1.0515611171722412
Epoch [4/10], Batch [45/100], Loss: 1.0964419841766357
Epoch [4/10], Batch [46/100], Loss: 1.1169229745864868
Epoch [4/10], Batch [47/100], Loss: 1.1606146097183228
Epoch [4/10], Batch [48/100], Loss: 1.037980556488037
Epoch [4/10], Batch [49/100], Loss: 1.092970609664917
Epoch [4/10], Batch [50/100], Loss: 1.040223240852356
Epoch [4/10], Batch [51/100], Loss: 1.1657754182815552
Epoch [4/10], Batch [52/100], Loss: 1.0416980981826782
Epoch [4/10], Batch [53/100], Loss: 1.0265181064605713
Epoch [4/10], Batch [54/100], Loss: 0.9932880997657776
Epoch [4/10], Batch [55/100], Loss: 1.025410771369934
Epoch [4/10], Batch [56/100], Loss: 1.0864778757095337
Epoch [4/10], Batch [57/100], Loss: 1.239917516708374
Epoch [4/10], Batch [58/100], Loss: 1.1731972694396973
Epoch [4/10], Batch [59/100], Loss: 1.1083067655563354
Epoch [4/10], Batch [60/100], Loss: 1.137032389640808
Epoch [4/10], Batch [61/100], Loss: 1.1086535453796387
Epoch [4/10], Batch [62/100], Loss: 1.0003941059112549
Epoch [4/10], Batch [63/100], Loss: 1.1727664470672607
Epoch [4/10], Batch [64/100], Loss: 1.221083164215088

In [9]:
X_test = torch.rand(1, 10, 50)  # Test data with 10 sequences
with torch.no_grad():
    predictions = model(X_test)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

Predicted Labels: tensor([1])

## Gestures Application

### Initial Inference Test

In [10]:
stationary_df = pl.read_csv("./imu_data/rosbag/data/data_clean/rosbag2_2023_03_02-05_19_45_data.csv")

stationary_df

shape: (100, 45)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ Imu0_line ┆ Imu0_line ┆ Imu0_line ┆ … ┆ imu0_to_i ┆ imu0_to_i ┆ imu0_to_i ┆ imu0_to_ │
│ ---       ┆ ar_accler ┆ ar_accler ┆ ar_accler ┆   ┆ mu2_rotat ┆ mu2_rotat ┆ mu2_rotat ┆ imu2_rot │
│ f64       ┆ ation_x   ┆ ation_y   ┆ ation_z   ┆   ┆ ion_x     ┆ ion_y     ┆ ion_z     ┆ ation_w  │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1.6777e9  ┆ -2.23     ┆ 5.5       ┆ 7.67      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.25     ┆ 5.48      ┆ 7.62      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.23     ┆ 5.49      ┆ 7.62      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.21     ┆ 5.54      ┆ 7.66      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.22     ┆ 5.58      ┆ 7.62      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1.6777e9  ┆ -0.27     ┆ 6.35      ┆ 7.25      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.28     ┆ 6.37      ┆ 7.21      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.29     ┆ 6.45      ┆ 7.2       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.29     ┆ 6.42      ┆ 7.08      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.25     ┆ 6.47      ┆ 7.12      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
def get_column_combos(imus, dims, readings):
    columns = [f"Imu{im}_{read}_{dim}" for im in imus for read in readings for dim in dims]
    return columns

imus = [0]
dims = ["x", "y", "z"]
readings = ["linear_accleration", "angular_velocity"]

X_one = stationary_df.select(
    get_column_combos(imus, dims, readings)
).to_torch(dtype=pl.Float32)

X_one.shape

torch.Size([100, 6])

In [12]:
stationary_df_label = pl.read_csv("./imu_data/rosbag/data/label/rosbag2_2023_03_02-05_19_45_label.csv")

stationary_df_label

shape: (1, 1)
┌───────┐
│ label │
│ ---   │
│ i64   │
╞═══════╡
│ 2     │
└───────┘

In [13]:
y_one = stationary_df_label.with_columns(
    pl.col('label').replace(10, 7)
).to_torch()[0]

y_one

tensor([2])

In [14]:
classes = {
    'STATIC': 0,
    'SLIDE_UP': 1,
    'SLIDE_DOWN': 2,
    'SLIDE_LEFT': 3,
    'SLIDE_RIGHT': 4,
    'RELEASE': 5,
    'GRASP': 6,
    'NONE': 7 # originally 10
}

input_size = 6
hidden_size = 64
num_layers = 1
output_size = len(classes)

model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
model

LSTMClassifier(
  (lstm): LSTM(6, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=8, bias=True)
)

In [15]:
X_one.unsqueeze(0).shape

torch.Size([1, 100, 6])

In [16]:
with torch.no_grad():
    predictions = model(X_one.unsqueeze(0))
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

Predicted Labels: tensor([7])

### Data Loading

In [83]:
class IMUDataSet(Dataset):
    def __init__(
            self,
            data_dir: str,
            labels_dir: str,
            class_mappings: list[tuple[int, int]] = [(10, 7)],
            mean: Optional[torch.Tensor] = None,
            std: Optional[torch.Tensor] = None,
            normalize: bool = False):
        super().__init__()
        self.data_dir = data_dir
        self.labels_dir = labels_dir
        self.data_paths = os.listdir(self.data_dir)
        self.label_paths = os.listdir(self.labels_dir)
        self.class_mappings = class_mappings
        self.mean = mean
        self.std = std
        self.normalize = normalize
        self.cache = {}
        self.imus = [0]
        self.dims = ["x", "y", "z"]
        self.readings = ["linear_accleration", "angular_velocity"]
        self.label_col = "label"
        self.epsilon = 1e-7

    def __len__(self):
        return len(self.data_paths)

    def __getitem__(self, idx):
        data, label = self.cache.get(idx, (None, None))
        if data is not None and label is not None:
            return data, label
        
        data_df = pl.read_csv(os.path.join(self.data_dir, self.data_paths[idx]))
        X_item = data_df.select(
            self.get_column_combos()
        ).to_torch(dtype=pl.Float32)
        
        label_df = pl.read_csv(os.path.join(self.labels_dir, self.label_paths[idx]))
        y_item = label_df.with_columns(
            (pl.col(self.label_col).replace(before, after) for before, after in self.class_mappings)
        ).to_torch()[0]

        # if self.min_val is not None and self.max_val is not None:
        #     X_item = (X_item - self.min_val) / (self.max_val - self.min_val + self.epsilon)
        if self.normalize and self.mean is not None and self.std is not None:
            X_item = (X_item - self.mean) / self.std

        # if X_item.shape[0] > 100:
        #     print(X_item.shape[0], y_item)

        try:
            self.cache[idx] = X_item, y_item
        except OSError:
            del self.cache[list(self.cache.keys())[0]]

        return X_item, y_item
    
    def get_column_combos(self):
        columns = [f"Imu{im}_{read}_{dim}" for im in self.imus for read in self.readings for dim in self.dims]
        return columns

In [18]:
a = torch.ones(5, 2)
b = torch.ones(4, 2)
c = torch.ones(3, 2)
pad_sequence([a, b, c], batch_first=True, padding_side="left")

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [94]:
def get_norm_values(data_loader: DataLoader):
    X_list = [X[0] for X, _ in data_loader]
    X_tensor = torch.cat(X_list)
    return X_tensor.mean(dim=0), X_tensor.std(dim=0)

temp_dataset = IMUDataSet("./imu_data/rosbag/data/data_clean", "./imu_data/rosbag/data/label")

temp_loader = torch.utils.data.DataLoader(temp_dataset,
        batch_size=1,
        shuffle=False
    )

mean, std = get_norm_values(temp_loader)
print("Mean:", mean)
print("STD:", std)

Mean: tensor([-0.7395,  4.8429,  3.3637,  0.0850,  0.0463,  0.0117])
STD: tensor([5.7835, 3.3225, 4.3546, 0.7242, 0.9477, 0.5873])

In [20]:
torch.ones(2, 5, 3) / torch.tensor([2, 3, 4])

tensor([[[0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500]],

        [[0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500]]])

In [114]:
def pad_collate(batch):
    tensors, targets = zip(*batch)
    data = pad_sequence(tensors, batch_first=True, padding_side="left")
    labels = torch.cat(targets)
    return data, labels

batch_size = 1
# min_val = torch.Tensor([-19.61, -19.61, -19.61, -4.36, -4.36, -4.36])
# max_val = torch.Tensor([19.61, 19.61, 19.61, 4.36, 4.36, 4.36])

full_dataset = IMUDataSet(
    "./imu_data/rosbag/data/data_clean", 
    "./imu_data/rosbag/data/label",
    mean=mean,
    std=std,
    normalize=True
)
#train_set, val_set = random_split(full_dataset, [0.95, 0.05])

# train_loader = torch.utils.data.DataLoader(train_set,
#     batch_size=batch_size,
#     collate_fn=pad_collate,
#     shuffle=True
# )

### Training

In [124]:
def reset_weights(m):
  '''
    Try resetting model weights to avoid
    weight leakage.
  '''
  for layer in m.children():
    if hasattr(layer, 'reset_parameters'):
        print(f'Reset trainable parameters of layer = {layer}')
        layer.reset_parameters()

classes = {
    'STATIC': 0,
    'SLIDE_UP': 1,
    'SLIDE_DOWN': 2,
    'SLIDE_LEFT': 3,
    'SLIDE_RIGHT': 4,
    'RELEASE': 5,
    'GRASP': 6,
    'NONE': 7 # originally 10
}

input_size = 6
hidden_size = 24
num_layers = 1
output_size = len(classes)

# model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
# model

In [ ]:
k_folds = 5
# num_epochs = 200
# learning_rate = 0.0005
num_epochs = 75
learning_rate = 0.001
weight_decay = 0.0001

results = {}

criterion = nn.CrossEntropyLoss()
#optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# for epoch in range(num_epochs):
#     for X, y in train_loader:
#         y_hat = model(X)
#         loss = criterion(y_hat, y)
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()
#     print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

kfold = KFold(n_splits=k_folds, shuffle=True)

# Start print
print('--------------------------------')

# K-fold Cross Validation model evaluation
for fold, (train_ids, test_ids) in enumerate(kfold.split(full_dataset)):

    # Print
    print(f'FOLD {fold}')
    print('--------------------------------')

    # Sample elements randomly from a given list of ids, no replacement.
    train_subsampler = torch.utils.data.SubsetRandomSampler(train_ids)
    test_subsampler = torch.utils.data.SubsetRandomSampler(test_ids)

    # Define data loaders for training and testing data in this fold
    trainloader = torch.utils.data.DataLoader(
                        full_dataset,
                        batch_size=batch_size,
                        collate_fn=pad_collate,
                        sampler=train_subsampler
    )
    testloader = torch.utils.data.DataLoader(
                        full_dataset,
                        batch_size=batch_size,
                        collate_fn=pad_collate,
                        sampler=test_subsampler
    )

    # Init the neural network
    model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
    model.apply(reset_weights)

    # Initialize optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

    # Run the training loop for defined number of epochs
    for epoch in range(0, num_epochs):

        # Print epoch
        print(f'Starting epoch {epoch+1}')

        # Set current loss value
        current_loss = 0.0

        # Iterate over the DataLoader for training data
        for i, data in enumerate(trainloader, 0):
        
            # Get inputs
            inputs, targets = data
            
            # Zero the gradients
            optimizer.zero_grad()
            
            # Perform forward pass
            outputs = model(inputs)
            
            # Compute loss
            loss = criterion(outputs, targets)
            
            # Perform backward pass
            loss.backward()
            
            # Perform optimization
            optimizer.step()
            
            # Print statistics
            current_loss += loss.item()
            if i % 500 == 499:
                print('Loss after mini-batch %5d: %.3f' %
                        (i + 1, current_loss / 500))
                current_loss = 0.0
            
    # Process is complete.
    print('Training process has finished. Saving trained model.')

    # Print about testing
    print('Starting testing')

    # Saving the model
    save_path = f'./model/model-fold-{fold}.pth'
    torch.save(model.state_dict(), save_path)

    # Evaluationfor this fold
    correct, total = 0, 0
    with torch.no_grad():

        # Iterate over the test data and generate predictions
        for i, data in enumerate(testloader, 0):

            # Get inputs
            inputs, targets = data

            # Generate outputs
            outputs = model(inputs)

            # Set total and correct
            _, predicted = torch.max(outputs.data, 1)
            total += targets.size(0)
            correct += (predicted == targets).sum().item()

        # Print accuracy
        print('Accuracy for fold %d: %d %%' % (fold, 100.0 * correct / total))
        print('--------------------------------')
        results[fold] = 100.0 * (correct / total)

--------------------------------
FOLD 0
--------------------------------

ValueError: sampler option is mutually exclusive with shuffle

In [128]:
# val_loader = torch.utils.data.DataLoader(val_set,
#         batch_size=len(val_set),
#         collate_fn=pad_collate,
#         shuffle=False
#     )

# # validation data
# val_X, val_y = next(iter(val_loader))
# Y_hat = model(val_X)
# val_loss = criterion(Y_hat, val_y)
# val_err = val_loss.item()

# print("Validation loss:", val_err)
fold = 2
save_path = f'./model/model-fold-{fold}.pth'
state_dict = torch.load(save_path, weights_only=True)
model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
model.load_state_dict(state_dict)
model

LSTMClassifier(
  (lstm): LSTM(6, 24, batch_first=True)
  (fc1): Linear(in_features=24, out_features=32, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=32, out_features=8, bias=True)
)

In [108]:
print(X_one.shape)
y_one

torch.Size([100, 6])

tensor([2])

In [129]:
#to_pred = ((X_one - min_val) / (max_val - min_val + 1e-7)).unsqueeze(0)
to_pred = ((X_one - mean) / std).unsqueeze(0)
#to_pred = X_one.unsqueeze(0)
with torch.no_grad():
    predictions = model(to_pred)
    print(predictions)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

tensor([[-0.3573, -0.4141,  0.0954, -1.2628, -0.0863, -0.5164, -0.3307, -0.3323]])
Predicted Labels: tensor([2])

In [130]:
X_another = pl.read_csv("./imu_data/rosbag/data/data_clean/rosbag2_2023_02_10-07_52_42_data.csv").select(
    get_column_combos(imus, dims, readings)
).to_torch(dtype=pl.Float32)

y_another = pl.read_csv("./imu_data/rosbag/data/label/rosbag2_2023_02_10-07_52_42_label.csv").with_columns(
    pl.col('label').replace(10, 7)
).to_torch()[0]

print(X_another.shape)
y_another

torch.Size([100, 6])

tensor([1])

In [131]:
#to_pred = ((X_another - min_val) / (max_val - min_val + 1e-7)).unsqueeze(0)
to_pred = ((X_another - mean) / std).unsqueeze(0)
#to_pred = X_another.unsqueeze(0)
with torch.no_grad():
    predictions = model(to_pred)
    print(predictions)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

tensor([[-1.4862, -1.0406, -0.4007, -0.2760, -0.2000, -0.4082, -0.2093,  0.0959]])
Predicted Labels: tensor([7])

In [132]:
X_another = pl.read_csv("./imu_data/rosbag/data/data_clean/rosbag2_2023_02_27-13_52_46_data.csv").select(
    get_column_combos(imus, dims, readings)
).to_torch(dtype=pl.Float32)

y_another = pl.read_csv("./imu_data/rosbag/data/label/rosbag2_2023_02_27-13_52_46_label.csv").with_columns(
    pl.col('label').replace(10, 7)
).to_torch()[0]

print(X_another.shape)
y_another

torch.Size([184, 6])

tensor([7])

In [133]:
#to_pred = ((X_another - min_val) / (max_val - min_val + 1e-7)).unsqueeze(0)
to_pred = ((X_another - mean) / std).unsqueeze(0)
#to_pred = X_another.unsqueeze(0)
with torch.no_grad():
    predictions = model(to_pred)
    print(predictions)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

tensor([[ -9.6350, -14.2120,  -3.1778,  -4.8483,  -9.2261,  -1.3774,  -4.5930,
           1.1289]])
Predicted Labels: tensor([7])

In [293]:
X_another.shape

torch.Size([184, 6])

In [294]:
X_one.shape

torch.Size([100, 6])

In [295]:
torch.cat([X_another, X_one]).shape

torch.Size([284, 6])

## ONNX Export

In [296]:
X_one.unsqueeze(0).shape

torch.Size([1, 100, 6])

In [134]:
model_path = "./model/gesture_rec_static.onnx"
input_name = "readings"
output_name = "gesture"
input_tensor = torch.randn(1, 100, 6)#X_one.unsqueeze(0)

model.eval()

torch.onnx.export(
    model,
    input_tensor,
    model_path,
    input_names = [input_name],
    output_names = [output_name],
    # dynamic_shapes=({
    #     0: torch.export.Dim.DYNAMIC,
    #     1: torch.export.Dim.DYNAMIC
    # },),
    # dynamic_shapes={
    #     'x': {
    #         0: "batch_size",
    #         1: "seq_len"
    #     }
    # },
    # dynamic_axes={
    #     input_name: {
    #         0: "batch_size",
    #         1: "seq_len"
    #     },
    #     output_name: {
    #         0: "batch_size",
    #         1: "seq_len" 
    #     }
    # },
    dynamo=False,
    external_data=False
)

/home/kojo/tmp/ipykernel_36500/1916155734.py:8: DeprecationWarning: You are using the legacy TorchScript-based ONNX export. Starting in PyTorch 2.9, the new torch.export-based ONNX exporter has become the default. Learn more about the new export logic: https://docs.pytorch.org/docs/stable/onnx_export.html. For exporting control flow: https://pytorch.org/tutorials/beginner/onnx/export_control_flow_model_to_onnx_tutorial.html
  torch.onnx.export(
/home/kojo/Code/730SemesterProject/exploration/imenv/lib/python3.12/site-packages/torch/onnx/_internal/torchscript_exporter/symbolic_opset9.py:4463: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  return _generic_rnn(

> Need to run onnxsim after this:

```bash
onnxsim ./model/gesture_rec_static.onnx ./model/gesture_rec_static_sim.onnx
```