In [263]:
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pad_sequence
import polars as pl
import os
from typing import Optional

## General Testing

In [ ]:
class LSTMClassifier(nn.Module):
    def __init__(self, input_size, hidden_dim, num_layers, output_size):
        super(LSTMClassifier, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size,
                            hidden_dim,
                            num_layers=num_layers,
                            batch_first=True
                           )
        self.fc = nn.Linear(hidden_dim, output_size)
        self.batch_size = 1
    
    def forward(self, x: torch.Tensor):
        #h = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(x.device)
        h = torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).to(x.device)
        c = torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).to(x.device)
        out, _ = self.lstm(x, (h, c))
        out = self.fc(out[:, -1, :])
        return out

In [265]:
# Generate sample data
X_train = torch.rand(100, 10, 50)  # 100 sequences of length 10 with 50 features each
y_train = torch.randint(3, size=(100,))  # Binary labels (0 or 1)

print(X_train.shape)
y_train

torch.Size([100, 10, 50])

tensor([0, 2, 0, 2, 1, 2, 1, 2, 2, 0, 2, 1, 0, 0, 2, 0, 2, 1, 1, 2, 1, 1, 1, 1,
        2, 2, 0, 2, 0, 1, 1, 2, 2, 1, 2, 1, 2, 2, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2,
        2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 1, 2, 1, 1,
        2, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 2, 1, 2, 2, 1, 0,
        2, 1, 0, 1])

In [266]:
y_train.unique(return_counts=True)

(tensor([0, 1, 2]), tensor([29, 32, 39]))

In [267]:
batch_size = 1
batches_X = X_train.split(batch_size)
batches_y = y_train.split(batch_size)
print(batches_X[-1].shape)
batches_y[-1].shape

torch.Size([1, 10, 50])

torch.Size([1])

In [268]:
input_size = 50
hidden_size = 64
num_layers = 1
output_size = 3

model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
model

LSTMClassifier(
  (lstm): LSTM(50, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=3, bias=True)
)

In [269]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

num_epochs = 10
for epoch in range(num_epochs):
    for bind in range(len(batches_X)):
        batch_X = batches_X[bind]
        batch_y = batches_y[bind]
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        print(f'Epoch [{epoch+1}/{num_epochs}], Batch [{bind}/{len(batches_X)}], Loss: {loss.item()}')

Epoch [1/10], Batch [0/100], Loss: 1.1070002317428589
Epoch [1/10], Batch [1/100], Loss: 1.4690642356872559
Epoch [1/10], Batch [2/100], Loss: 0.7362599968910217
Epoch [1/10], Batch [3/100], Loss: 0.9942346811294556
Epoch [1/10], Batch [4/100], Loss: 2.198991537094116
Epoch [1/10], Batch [5/100], Loss: 0.8074228167533875
Epoch [1/10], Batch [6/100], Loss: 1.9860937595367432
Epoch [1/10], Batch [7/100], Loss: 0.7048201560974121
Epoch [1/10], Batch [8/100], Loss: 0.6806858777999878
Epoch [1/10], Batch [9/100], Loss: 1.347013235092163
Epoch [1/10], Batch [10/100], Loss: 0.622641384601593
Epoch [1/10], Batch [11/100], Loss: 1.5659055709838867
Epoch [1/10], Batch [12/100], Loss: 1.4324272871017456
Epoch [1/10], Batch [13/100], Loss: 1.4043158292770386
Epoch [1/10], Batch [14/100], Loss: 0.680553138256073
Epoch [1/10], Batch [15/100], Loss: 1.309539556503296
Epoch [1/10], Batch [16/100], Loss: 0.7363902926445007
Epoch [1/10], Batch [17/100], Loss: 1.4696099758148193
Epoch [1/10], Batch [18/100], Loss: 1.441585898399353
Epoch [1/10], Batch [19/100], Loss: 0.7720369100570679
Epoch [1/10], Batch [20/100], Loss: 1.3799690008163452
Epoch [1/10], Batch [21/100], Loss: 1.3715412616729736
Epoch [1/10], Batch [22/100], Loss: 1.3198946714401245
Epoch [1/10], Batch [23/100], Loss: 1.2757686376571655
Epoch [1/10], Batch [24/100], Loss: 0.8934690356254578
Epoch [1/10], Batch [25/100], Loss: 0.9169606566429138
Epoch [1/10], Batch [26/100], Loss: 1.2450268268585205
Epoch [1/10], Batch [27/100], Loss: 0.9264984726905823
Epoch [1/10], Batch [28/100], Loss: 1.2422657012939453
Epoch [1/10], Batch [29/100], Loss: 1.1205494403839111
Epoch [1/10], Batch [30/100], Loss: 1.1143168210983276
Epoch [1/10], Batch [31/100], Loss: 0.9734815359115601
Epoch [1/10], Batch [32/100], Loss: 0.9717018604278564
Epoch [1/10], Batch [33/100], Loss: 1.0867862701416016
Epoch [1/10], Batch [34/100], Loss: 0.982196033000946
Epoch [1/10], Batch [35/100], Loss: 1.0563923120498657
Epoch [1/10], Batch [36/100], Loss: 0.9702194929122925
Epoch [1/10], Batch [37/100], Loss: 0.9822266101837158
Epoch [1/10], Batch [38/100], Loss: 1.355723261833191
Epoch [1/10], Batch [39/100], Loss: 1.3504453897476196
Epoch [1/10], Batch [40/100], Loss: 1.346147894859314
Epoch [1/10], Batch [41/100], Loss: 1.334241271018982
Epoch [1/10], Batch [42/100], Loss: 1.067142128944397
Epoch [1/10], Batch [43/100], Loss: 0.9707897305488586
Epoch [1/10], Batch [44/100], Loss: 1.0881835222244263
Epoch [1/10], Batch [45/100], Loss: 1.2746992111206055
Epoch [1/10], Batch [46/100], Loss: 1.2577285766601562
Epoch [1/10], Batch [47/100], Loss: 0.9773460030555725
Epoch [1/10], Batch [48/100], Loss: 0.9631626009941101
Epoch [1/10], Batch [49/100], Loss: 1.2374515533447266
Epoch [1/10], Batch [50/100], Loss: 0.9829525947570801
Epoch [1/10], Batch [51/100], Loss: 0.9639749526977539
Epoch [1/10], Batch [52/100], Loss: 1.2097556591033936
Epoch [1/10], Batch [53/100], Loss: 0.9585661292076111
Epoch [1/10], Batch [54/100], Loss: 0.9561593532562256
Epoch [1/10], Batch [55/100], Loss: 1.19990873336792
Epoch [1/10], Batch [56/100], Loss: 0.94808429479599
Epoch [1/10], Batch [57/100], Loss: 0.936317503452301
Epoch [1/10], Batch [58/100], Loss: 0.9291130304336548
Epoch [1/10], Batch [59/100], Loss: 1.1927778720855713
Epoch [1/10], Batch [60/100], Loss: 1.2021639347076416
Epoch [1/10], Batch [61/100], Loss: 0.914526104927063
Epoch [1/10], Batch [62/100], Loss: 0.8851956725120544
Epoch [1/10], Batch [63/100], Loss: 0.8719028234481812
Epoch [1/10], Batch [64/100], Loss: 0.8696421980857849
Epoch [1/10], Batch [65/100], Loss: 1.2112308740615845
Epoch [1/10], Batch [66/100], Loss: 1.1972969770431519
Epoch [1/10], Batch [67/100], Loss: 1.1926040649414062
Epoch [1/10], Batch [68/100], Loss: 1.3768888711929321
Epoch [1/10], Batch [69/100], Loss: 0.8151756525039673
Epoch [1/10], Batch [70/100], Loss: 1.392552137374878
Epoch [1/10], Batch [71/100], Loss: 1.426595687866211
Epoch [1/10], Batch [72/100], Loss: 0.8268523812294006
Epoch [1/10], Batch [73/100], Loss: 1.4025025367736816
Epoch [1/10], Batch [74/100], Loss: 1.1727116107940674
Epoch [1/10], Batch [75/100], Loss: 1.3569471836090088
Epoch [1/10], Batch [76/100], Loss: 1.3543455600738525
Epoch [1/10], Batch [77/100], Loss: 1.3422226905822754
Epoch [1/10], Batch [78/100], Loss: 1.3212990760803223
Epoch [1/10], Batch [79/100], Loss: 0.8867207765579224
Epoch [1/10], Batch [80/100], Loss: 1.178280234336853
Epoch [1/10], Batch [81/100], Loss: 1.2426350116729736
Epoch [1/10], Batch [82/100], Loss: 1.2417267560958862
Epoch [1/10], Batch [83/100], Loss: 1.1778777837753296
Epoch [1/10], Batch [84/100], Loss: 1.1932191848754883
Epoch [1/10], Batch [85/100], Loss: 1.1838154792785645
Epoch [1/10], Batch [86/100], Loss: 1.1808513402938843
Epoch [1/10], Batch [87/100], Loss: 0.9602890014648438
Epoch [1/10], Batch [88/100], Loss: 1.1631910800933838
Epoch [1/10], Batch [89/100], Loss: 1.175991415977478
Epoch [1/10], Batch [90/100], Loss: 0.9863771200180054
Epoch [1/10], Batch [91/100], Loss: 1.1356244087219238
Epoch [1/10], Batch [92/100], Loss: 0.9998637437820435
Epoch [1/10], Batch [93/100], Loss: 0.9992077350616455
Epoch [1/10], Batch [94/100], Loss: 1.1242555379867554
Epoch [1/10], Batch [95/100], Loss: 1.1787043809890747
Epoch [1/10], Batch [96/100], Loss: 0.9981921315193176
Epoch [1/10], Batch [97/100], Loss: 1.1139143705368042
Epoch [1/10], Batch [98/100], Loss: 1.1844799518585205
Epoch [1/10], Batch [99/100], Loss: 1.1106936931610107
Epoch [2/10], Batch [0/100], Loss: 1.1845667362213135
Epoch [2/10], Batch [1/100], Loss: 1.0089690685272217
Epoch [2/10], Batch [2/100], Loss: 1.1878818273544312
Epoch [2/10], Batch [3/100], Loss: 1.0134389400482178
Epoch [2/10], Batch [4/100], Loss: 1.1030101776123047
Epoch [2/10], Batch [5/100], Loss: 1.0160133838653564
Epoch [2/10], Batch [6/100], Loss: 1.1020655632019043
Epoch [2/10], Batch [7/100], Loss: 1.0207654237747192
Epoch [2/10], Batch [8/100], Loss: 1.009660243988037
Epoch [2/10], Batch [9/100], Loss: 1.1888229846954346
Epoch [2/10], Batch [10/100], Loss: 1.0105562210083008
Epoch [2/10], Batch [11/100], Loss: 1.1014304161071777
Epoch [2/10], Batch [12/100], Loss: 1.1897339820861816
Epoch [2/10], Batch [13/100], Loss: 1.1954814195632935
Epoch [2/10], Batch [14/100], Loss: 1.0112076997756958
Epoch [2/10], Batch [15/100], Loss: 1.1877156496047974
Epoch [2/10], Batch [16/100], Loss: 1.0074394941329956
Epoch [2/10], Batch [17/100], Loss: 1.1115473508834839
Epoch [2/10], Batch [18/100], Loss: 1.1129646301269531
Epoch [2/10], Batch [19/100], Loss: 0.9996826648712158
Epoch [2/10], Batch [20/100], Loss: 1.112465500831604
Epoch [2/10], Batch [21/100], Loss: 1.1127591133117676
Epoch [2/10], Batch [22/100], Loss: 1.1085984706878662
Epoch [2/10], Batch [23/100], Loss: 1.1033909320831299
Epoch [2/10], Batch [24/100], Loss: 1.0030642747879028
Epoch [2/10], Batch [25/100], Loss: 1.0062106847763062
Epoch [2/10], Batch [26/100], Loss: 1.2002662420272827
Epoch [2/10], Batch [27/100], Loss: 1.006897211074829
Epoch [2/10], Batch [28/100], Loss: 1.2041445970535278
Epoch [2/10], Batch [29/100], Loss: 1.0912212133407593
Epoch [2/10], Batch [30/100], Loss: 1.0904356241226196
Epoch [2/10], Batch [31/100], Loss: 1.0027796030044556
Epoch [2/10], Batch [32/100], Loss: 1.0015865564346313
Epoch [2/10], Batch [33/100], Loss: 1.0880132913589478
Epoch [2/10], Batch [34/100], Loss: 1.0006674528121948
Epoch [2/10], Batch [35/100], Loss: 1.0822254419326782
Epoch [2/10], Batch [36/100], Loss: 0.98698890209198
Epoch [2/10], Batch [37/100], Loss: 0.9960906505584717
Epoch [2/10], Batch [38/100], Loss: 1.2468786239624023
Epoch [2/10], Batch [39/100], Loss: 1.2477855682373047
Epoch [2/10], Batch [40/100], Loss: 1.245160698890686
Epoch [2/10], Batch [41/100], Loss: 1.2456939220428467
Epoch [2/10], Batch [42/100], Loss: 1.0856778621673584
Epoch [2/10], Batch [43/100], Loss: 0.9938219785690308
Epoch [2/10], Batch [44/100], Loss: 1.0896364450454712
Epoch [2/10], Batch [45/100], Loss: 1.2354453802108765
Epoch [2/10], Batch [46/100], Loss: 1.2316597700119019
Epoch [2/10], Batch [47/100], Loss: 0.9890519380569458
Epoch [2/10], Batch [48/100], Loss: 0.9785101413726807
Epoch [2/10], Batch [49/100], Loss: 1.2270255088806152
Epoch [2/10], Batch [50/100], Loss: 0.9932209849357605
Epoch [2/10], Batch [51/100], Loss: 0.979220449924469
Epoch [2/10], Batch [52/100], Loss: 1.2163152694702148
Epoch [2/10], Batch [53/100], Loss: 0.9758533835411072
Epoch [2/10], Batch [54/100], Loss: 0.9773969054222107
Epoch [2/10], Batch [55/100], Loss: 1.2121148109436035
Epoch [2/10], Batch [56/100], Loss: 0.9703069925308228
Epoch [2/10], Batch [57/100], Loss: 0.9596049189567566
Epoch [2/10], Batch [58/100], Loss: 0.9437866806983948
Epoch [2/10], Batch [59/100], Loss: 1.214967966079712
Epoch [2/10], Batch [60/100], Loss: 1.2234370708465576
Epoch [2/10], Batch [61/100], Loss: 0.9377294182777405
Epoch [2/10], Batch [62/100], Loss: 0.910179615020752
Epoch [2/10], Batch [63/100], Loss: 0.8805716037750244
Epoch [2/10], Batch [64/100], Loss: 0.849953830242157
Epoch [2/10], Batch [65/100], Loss: 1.250443935394287
Epoch [2/10], Batch [66/100], Loss: 1.2359564304351807
Epoch [2/10], Batch [67/100], Loss: 1.219795823097229
Epoch [2/10], Batch [68/100], Loss: 1.4531272649765015
Epoch [2/10], Batch [69/100], Loss: 0.7724217772483826
Epoch [2/10], Batch [70/100], Loss: 1.4532043933868408
Epoch [2/10], Batch [71/100], Loss: 1.4553691148757935
Epoch [2/10], Batch [72/100], Loss: 0.7984938025474548
Epoch [2/10], Batch [73/100], Loss: 1.406416893005371
Epoch [2/10], Batch [74/100], Loss: 1.1718026399612427
Epoch [2/10], Batch [75/100], Loss: 1.3719837665557861
Epoch [2/10], Batch [76/100], Loss: 1.3557746410369873
Epoch [2/10], Batch [77/100], Loss: 1.337143898010254
Epoch [2/10], Batch [78/100], Loss: 1.3134288787841797
Epoch [2/10], Batch [79/100], Loss: 0.8895547389984131
Epoch [2/10], Batch [80/100], Loss: 1.1845207214355469
Epoch [2/10], Batch [81/100], Loss: 1.2244584560394287
Epoch [2/10], Batch [82/100], Loss: 1.2160279750823975
Epoch [2/10], Batch [83/100], Loss: 1.1898150444030762
Epoch [2/10], Batch [84/100], Loss: 1.175693392753601
Epoch [2/10], Batch [85/100], Loss: 1.1984305381774902
Epoch [2/10], Batch [86/100], Loss: 1.1546580791473389
Epoch [2/10], Batch [87/100], Loss: 0.968885600566864
Epoch [2/10], Batch [88/100], Loss: 1.138024926185608
Epoch [2/10], Batch [89/100], Loss: 1.1931397914886475
Epoch [2/10], Batch [90/100], Loss: 0.989952027797699
Epoch [2/10], Batch [91/100], Loss: 1.1171015501022339
Epoch [2/10], Batch [92/100], Loss: 1.0030832290649414
Epoch [2/10], Batch [93/100], Loss: 0.9997769594192505
Epoch [2/10], Batch [94/100], Loss: 1.1078578233718872
Epoch [2/10], Batch [95/100], Loss: 1.1984572410583496
Epoch [2/10], Batch [96/100], Loss: 0.9994062781333923
Epoch [2/10], Batch [97/100], Loss: 1.1000733375549316
Epoch [2/10], Batch [98/100], Loss: 1.2030339241027832
Epoch [2/10], Batch [99/100], Loss: 1.0978153944015503
Epoch [3/10], Batch [0/100], Loss: 1.2015217542648315
Epoch [3/10], Batch [1/100], Loss: 1.0024621486663818
Epoch [3/10], Batch [2/100], Loss: 1.2045166492462158
Epoch [3/10], Batch [3/100], Loss: 1.0068109035491943
Epoch [3/10], Batch [4/100], Loss: 1.092598795890808
Epoch [3/10], Batch [5/100], Loss: 1.008588194847107
Epoch [3/10], Batch [6/100], Loss: 1.0928821563720703
Epoch [3/10], Batch [7/100], Loss: 1.0122222900390625
Epoch [3/10], Batch [8/100], Loss: 1.0035457611083984
Epoch [3/10], Batch [9/100], Loss: 1.2075331211090088
Epoch [3/10], Batch [10/100], Loss: 1.002051591873169
Epoch [3/10], Batch [11/100], Loss: 1.0947781801223755
Epoch [3/10], Batch [12/100], Loss: 1.2076879739761353
Epoch [3/10], Batch [13/100], Loss: 1.212519645690918
Epoch [3/10], Batch [14/100], Loss: 1.000622034072876
Epoch [3/10], Batch [15/100], Loss: 1.2065327167510986
Epoch [3/10], Batch [16/100], Loss: 0.9985569715499878
Epoch [3/10], Batch [17/100], Loss: 1.1058077812194824
Epoch [3/10], Batch [18/100], Loss: 1.1066337823867798
Epoch [3/10], Batch [19/100], Loss: 0.9889711737632751
Epoch [3/10], Batch [20/100], Loss: 1.1066843271255493
Epoch [3/10], Batch [21/100], Loss: 1.1083543300628662
Epoch [3/10], Batch [22/100], Loss: 1.1034458875656128
Epoch [3/10], Batch [23/100], Loss: 1.097104549407959
Epoch [3/10], Batch [24/100], Loss: 0.9906109571456909
Epoch [3/10], Batch [25/100], Loss: 0.9952143430709839
Epoch [3/10], Batch [26/100], Loss: 1.2160639762878418
Epoch [3/10], Batch [27/100], Loss: 0.9965755343437195
Epoch [3/10], Batch [28/100], Loss: 1.2214621305465698
Epoch [3/10], Batch [29/100], Loss: 1.0855915546417236
Epoch [3/10], Batch [30/100], Loss: 1.086366891860962
Epoch [3/10], Batch [31/100], Loss: 0.9929363131523132
Epoch [3/10], Batch [32/100], Loss: 0.9935776591300964
Epoch [3/10], Batch [33/100], Loss: 1.084430456161499
Epoch [3/10], Batch [34/100], Loss: 0.9913234114646912
Epoch [3/10], Batch [35/100], Loss: 1.0798513889312744
Epoch [3/10], Batch [36/100], Loss: 0.9762065410614014
Epoch [3/10], Batch [37/100], Loss: 0.9860741496086121
Epoch [3/10], Batch [38/100], Loss: 1.2621996402740479
Epoch [3/10], Batch [39/100], Loss: 1.262941837310791
Epoch [3/10], Batch [40/100], Loss: 1.2588961124420166
Epoch [3/10], Batch [41/100], Loss: 1.2577488422393799
Epoch [3/10], Batch [42/100], Loss: 1.0830121040344238
Epoch [3/10], Batch [43/100], Loss: 0.9839346408843994
Epoch [3/10], Batch [44/100], Loss: 1.0869957208633423
Epoch [3/10], Batch [45/100], Loss: 1.2475253343582153
Epoch [3/10], Batch [46/100], Loss: 1.2462658882141113
Epoch [3/10], Batch [47/100], Loss: 0.9802190661430359
Epoch [3/10], Batch [48/100], Loss: 0.9648153781890869
Epoch [3/10], Batch [49/100], Loss: 1.2408908605575562
Epoch [3/10], Batch [50/100], Loss: 0.983496904373169
Epoch [3/10], Batch [51/100], Loss: 0.9660722017288208
Epoch [3/10], Batch [52/100], Loss: 1.2324775457382202
Epoch [3/10], Batch [53/100], Loss: 0.9681324362754822
Epoch [3/10], Batch [54/100], Loss: 0.9696268439292908
Epoch [3/10], Batch [55/100], Loss: 1.2261004447937012
Epoch [3/10], Batch [56/100], Loss: 0.96174556016922
Epoch [3/10], Batch [57/100], Loss: 0.944899320602417
Epoch [3/10], Batch [58/100], Loss: 0.9312768578529358
Epoch [3/10], Batch [59/100], Loss: 1.2292299270629883
Epoch [3/10], Batch [60/100], Loss: 1.2364859580993652
Epoch [3/10], Batch [61/100], Loss: 0.9329220056533813
Epoch [3/10], Batch [62/100], Loss: 0.9046069979667664
Epoch [3/10], Batch [63/100], Loss: 0.8892285823822021
Epoch [3/10], Batch [64/100], Loss: 0.888332188129425
Epoch [3/10], Batch [65/100], Loss: 1.2563263177871704
Epoch [3/10], Batch [66/100], Loss: 1.247154712677002
Epoch [3/10], Batch [67/100], Loss: 1.2366937398910522
Epoch [3/10], Batch [68/100], Loss: 1.2572606801986694
Epoch [3/10], Batch [69/100], Loss: 0.8315612077713013
Epoch [3/10], Batch [70/100], Loss: 1.2646195888519287
Epoch [3/10], Batch [71/100], Loss: 1.2996711730957031
Epoch [3/10], Batch [72/100], Loss: 0.8462477922439575
Epoch [3/10], Batch [73/100], Loss: 1.2625809907913208
Epoch [3/10], Batch [74/100], Loss: 1.2222316265106201
Epoch [3/10], Batch [75/100], Loss: 1.2387421131134033
Epoch [3/10], Batch [76/100], Loss: 1.2391881942749023
Epoch [3/10], Batch [77/100], Loss: 1.2355444431304932
Epoch [3/10], Batch [78/100], Loss: 1.234327793121338
Epoch [3/10], Batch [79/100], Loss: 0.9010010957717896
Epoch [3/10], Batch [80/100], Loss: 1.2206300497055054
Epoch [3/10], Batch [81/100], Loss: 1.1901346445083618
Epoch [3/10], Batch [82/100], Loss: 1.1904000043869019
Epoch [3/10], Batch [83/100], Loss: 1.2192822694778442
Epoch [3/10], Batch [84/100], Loss: 1.164056658744812
Epoch [3/10], Batch [85/100], Loss: 1.2249305248260498
Epoch [3/10], Batch [86/100], Loss: 1.1579777002334595
Epoch [3/10], Batch [87/100], Loss: 0.9453110098838806
Epoch [3/10], Batch [88/100], Loss: 1.1450986862182617
Epoch [3/10], Batch [89/100], Loss: 1.2073404788970947
Epoch [3/10], Batch [90/100], Loss: 0.9666391015052795
Epoch [3/10], Batch [91/100], Loss: 1.126163125038147
Epoch [3/10], Batch [92/100], Loss: 0.9826477766036987
Epoch [3/10], Batch [93/100], Loss: 0.980583667755127
Epoch [3/10], Batch [94/100], Loss: 1.1175079345703125
Epoch [3/10], Batch [95/100], Loss: 1.2077220678329468
Epoch [3/10], Batch [96/100], Loss: 0.9772849082946777
Epoch [3/10], Batch [97/100], Loss: 1.1090505123138428
Epoch [3/10], Batch [98/100], Loss: 1.210648775100708
Epoch [3/10], Batch [99/100], Loss: 1.106502890586853
Epoch [4/10], Batch [0/100], Loss: 1.2068886756896973
Epoch [4/10], Batch [1/100], Loss: 0.9872329831123352
Epoch [4/10], Batch [2/100], Loss: 1.2106164693832397
Epoch [4/10], Batch [3/100], Loss: 0.9912042617797852
Epoch [4/10], Batch [4/100], Loss: 1.101461410522461
Epoch [4/10], Batch [5/100], Loss: 0.9929395318031311
Epoch [4/10], Batch [6/100], Loss: 1.1020218133926392
Epoch [4/10], Batch [7/100], Loss: 0.9994152784347534
Epoch [4/10], Batch [8/100], Loss: 0.9880881905555725
Epoch [4/10], Batch [9/100], Loss: 1.21477210521698
Epoch [4/10], Batch [10/100], Loss: 0.9887183904647827
Epoch [4/10], Batch [11/100], Loss: 1.1029114723205566
Epoch [4/10], Batch [12/100], Loss: 1.211565375328064
Epoch [4/10], Batch [13/100], Loss: 1.2157849073410034
Epoch [4/10], Batch [14/100], Loss: 0.9898919463157654
Epoch [4/10], Batch [15/100], Loss: 1.2124218940734863
Epoch [4/10], Batch [16/100], Loss: 0.9884499907493591
Epoch [4/10], Batch [17/100], Loss: 1.112470030784607
Epoch [4/10], Batch [18/100], Loss: 1.1142404079437256
Epoch [4/10], Batch [19/100], Loss: 0.9773016571998596
Epoch [4/10], Batch [20/100], Loss: 1.1135542392730713
Epoch [4/10], Batch [21/100], Loss: 1.1154447793960571
Epoch [4/10], Batch [22/100], Loss: 1.1101621389389038
Epoch [4/10], Batch [23/100], Loss: 1.1022011041641235
Epoch [4/10], Batch [24/100], Loss: 0.9778146147727966
Epoch [4/10], Batch [25/100], Loss: 0.9839542508125305
Epoch [4/10], Batch [26/100], Loss: 1.2170947790145874
Epoch [4/10], Batch [27/100], Loss: 0.988070547580719
Epoch [4/10], Batch [28/100], Loss: 1.226511836051941
Epoch [4/10], Batch [29/100], Loss: 1.0913490056991577
Epoch [4/10], Batch [30/100], Loss: 1.0915138721466064
Epoch [4/10], Batch [31/100], Loss: 0.9825423955917358
Epoch [4/10], Batch [32/100], Loss: 0.9874141216278076
Epoch [4/10], Batch [33/100], Loss: 1.0892530679702759
Epoch [4/10], Batch [34/100], Loss: 0.9820229411125183
Epoch [4/10], Batch [35/100], Loss: 1.0852917432785034
Epoch [4/10], Batch [36/100], Loss: 0.9639176726341248
Epoch [4/10], Batch [37/100], Loss: 0.9762293100357056
Epoch [4/10], Batch [38/100], Loss: 1.2692244052886963
Epoch [4/10], Batch [39/100], Loss: 1.2690346240997314
Epoch [4/10], Batch [40/100], Loss: 1.263932228088379
Epoch [4/10], Batch [41/100], Loss: 1.2641746997833252
Epoch [4/10], Batch [42/100], Loss: 1.0872156620025635
Epoch [4/10], Batch [43/100], Loss: 0.9742744565010071
Epoch [4/10], Batch [44/100], Loss: 1.0911750793457031
Epoch [4/10], Batch [45/100], Loss: 1.2516971826553345
Epoch [4/10], Batch [46/100], Loss: 1.2534892559051514
Epoch [4/10], Batch [47/100], Loss: 0.9698717594146729
Epoch [4/10], Batch [48/100], Loss: 0.9515457153320312
Epoch [4/10], Batch [49/100], Loss: 1.244776725769043
Epoch [4/10], Batch [50/100], Loss: 0.973115861415863
Epoch [4/10], Batch [51/100], Loss: 0.9547637104988098
Epoch [4/10], Batch [52/100], Loss: 1.2383854389190674
Epoch [4/10], Batch [53/100], Loss: 0.955867350101471
Epoch [4/10], Batch [54/100], Loss: 0.960431694984436
Epoch [4/10], Batch [55/100], Loss: 1.2297945022583008
Epoch [4/10], Batch [56/100], Loss: 0.9491725564002991
Epoch [4/10], Batch [57/100], Loss: 0.9294384121894836
Epoch [4/10], Batch [58/100], Loss: 0.9081379175186157
Epoch [4/10], Batch [59/100], Loss: 1.2431269884109497
Epoch [4/10], Batch [60/100], Loss: 1.2430412769317627
Epoch [4/10], Batch [61/100], Loss: 0.9174262881278992
Epoch [4/10], Batch [62/100], Loss: 0.8834807276725769
Epoch [4/10], Batch [63/100], Loss: 0.8583449125289917
Epoch [4/10], Batch [64/100], Loss: 0.8509734272956848

In [271]:
X_test = torch.rand(1, 10, 50)  # Test data with 10 sequences
with torch.no_grad():
    predictions = model(X_test)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

Predicted Labels: tensor([1])

## Gestures Application

### Initial Inference Test

In [272]:
stationary_df = pl.read_csv("./imu_data/rosbag/data/data_clean/rosbag2_2023_03_02-05_19_45_data.csv")

stationary_df

shape: (100, 45)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ Imu0_line ┆ Imu0_line ┆ Imu0_line ┆ … ┆ imu0_to_i ┆ imu0_to_i ┆ imu0_to_i ┆ imu0_to_ │
│ ---       ┆ ar_accler ┆ ar_accler ┆ ar_accler ┆   ┆ mu2_rotat ┆ mu2_rotat ┆ mu2_rotat ┆ imu2_rot │
│ f64       ┆ ation_x   ┆ ation_y   ┆ ation_z   ┆   ┆ ion_x     ┆ ion_y     ┆ ion_z     ┆ ation_w  │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1.6777e9  ┆ -2.23     ┆ 5.5       ┆ 7.67      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.25     ┆ 5.48      ┆ 7.62      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.23     ┆ 5.49      ┆ 7.62      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.21     ┆ 5.54      ┆ 7.66      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -2.22     ┆ 5.58      ┆ 7.62      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1.6777e9  ┆ -0.27     ┆ 6.35      ┆ 7.25      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.28     ┆ 6.37      ┆ 7.21      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.29     ┆ 6.45      ┆ 7.2       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.29     ┆ 6.42      ┆ 7.08      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
│ 1.6777e9  ┆ -0.25     ┆ 6.47      ┆ 7.12      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [273]:
def get_column_combos(imus, dims, readings):
    columns = [f"Imu{im}_{read}_{dim}" for im in imus for read in readings for dim in dims]
    return columns

imus = [0]
dims = ["x", "y", "z"]
readings = ["linear_accleration", "angular_velocity"]

X_one = stationary_df.select(
    get_column_combos(imus, dims, readings)
).to_torch(dtype=pl.Float32)

X_one.shape

torch.Size([100, 6])

In [274]:
stationary_df_label = pl.read_csv("./imu_data/rosbag/data/label/rosbag2_2023_03_02-05_19_45_label.csv")

stationary_df_label

shape: (1, 1)
┌───────┐
│ label │
│ ---   │
│ i64   │
╞═══════╡
│ 2     │
└───────┘

In [275]:
y_one = stationary_df_label.with_columns(
    pl.col('label').replace(10, 7)
).to_torch()[0]

y_one

tensor([2])

In [276]:
classes = {
    'STATIC': 0,
    'SLIDE_UP': 1,
    'SLIDE_DOWN': 2,
    'SLIDE_LEFT': 3,
    'SLIDE_RIGHT': 4,
    'RELEASE': 5,
    'GRASP': 6,
    'NONE': 7 # originally 10
}

input_size = 6
hidden_size = 64
num_layers = 1
output_size = len(classes)

model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
model

LSTMClassifier(
  (lstm): LSTM(6, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=8, bias=True)
)

In [277]:
X_one.unsqueeze(0).shape

torch.Size([1, 100, 6])

In [278]:
with torch.no_grad():
    predictions = model(X_one.unsqueeze(0))
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

Predicted Labels: tensor([6])

### Data Loading

In [279]:
class IMUDataSet(Dataset):
    def __init__(
            self,
            data_dir: str,
            labels_dir: str,
            class_mappings: list[tuple[int, int]] = [(10, 7)],
            mean: Optional[torch.Tensor] = None,
            std: Optional[torch.Tensor] = None,
            normalize: bool = False):
        super().__init__()
        self.data_dir = data_dir
        self.labels_dir = labels_dir
        self.data_paths = os.listdir(self.data_dir)
        self.label_paths = os.listdir(self.labels_dir)
        self.class_mappings = class_mappings
        self.mean = mean
        self.std = std
        self.normalize = normalize
        self.cache = {}
        self.imus = [0]
        self.dims = ["x", "y", "z"]
        self.readings = ["linear_accleration", "angular_velocity"]
        self.label_col = "label"
        self.epsilon = 1e-7

    def __len__(self):
        return len(self.data_paths)

    def __getitem__(self, idx):
        data, label = self.cache.get(idx, (None, None))
        if data is not None and label is not None:
            return data, label
        
        data_df = pl.read_csv(os.path.join(self.data_dir, self.data_paths[idx]))
        X_item = data_df.select(
            self.get_column_combos()
        ).to_torch(dtype=pl.Float32)
        
        label_df = pl.read_csv(os.path.join(self.labels_dir, self.label_paths[idx]))
        y_item = label_df.with_columns(
            (pl.col(self.label_col).replace(before, after) for before, after in self.class_mappings)
        ).to_torch()[0]

        # if self.min_val is not None and self.max_val is not None:
        #     X_item = (X_item - self.min_val) / (self.max_val - self.min_val + self.epsilon)
        if self.normalize and self.mean is not None and self.std is not None:
            X_item = (X_item - self.mean) / self.std

        # if X_item.shape[0] > 100:
        #     print(X_item.shape[0], y_item)

        try:
            self.cache[idx] = X_item, y_item
        except OSError:
            del self.cache[list(self.cache.keys())[0]]

        return X_item, y_item
    
    def get_column_combos(self):
        columns = [f"Imu{im}_{read}_{dim}" for im in self.imus for read in self.readings for dim in self.dims]
        return columns

In [280]:
a = torch.ones(5, 2)
b = torch.ones(4, 2)
c = torch.ones(3, 2)
pad_sequence([a, b, c], batch_first=True, padding_side="left")

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [281]:
def get_norm_values(data_loader: DataLoader):
    X_list = [X[0] for X, _ in data_loader]
    X_tensor = torch.cat(X_list)
    return X_tensor.mean(dim=0), X_tensor.std(dim=0)

temp_dataset = IMUDataSet("./imu_data/rosbag/data/data_clean", "./imu_data/rosbag/data/label")

temp_loader = torch.utils.data.DataLoader(temp_dataset,
        batch_size=1,
        shuffle=False
    )

mean, std = get_norm_values(temp_loader)
print("Mean:", mean)
print("STD:", std)

Mean: tensor([-0.7395,  4.8429,  3.3637,  0.0850,  0.0463,  0.0117])
STD: tensor([5.7835, 3.3225, 4.3546, 0.7242, 0.9477, 0.5873])

In [282]:
torch.ones(2, 5, 3) / torch.tensor([2, 3, 4])

tensor([[[0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500]],

        [[0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500],
         [0.5000, 0.3333, 0.2500]]])

In [283]:
def pad_collate(batch):
    tensors, targets = zip(*batch)
    data = pad_sequence(tensors, batch_first=True, padding_side="left")
    labels = torch.cat(targets)
    return data, labels

batch_size = 1
# min_val = torch.Tensor([-19.61, -19.61, -19.61, -4.36, -4.36, -4.36])
# max_val = torch.Tensor([19.61, 19.61, 19.61, 4.36, 4.36, 4.36])

full_dataset = IMUDataSet(
    "./imu_data/rosbag/data/data_clean", 
    "./imu_data/rosbag/data/label",
    mean=mean,
    std=std
)
train_set, val_set = random_split(full_dataset, [0.95, 0.05])

train_loader = torch.utils.data.DataLoader(train_set,
    batch_size=batch_size,
    collate_fn=pad_collate,
    shuffle=True
)

### Training

In [284]:
classes = {
    'STATIC': 0,
    'SLIDE_UP': 1,
    'SLIDE_DOWN': 2,
    'SLIDE_LEFT': 3,
    'SLIDE_RIGHT': 4,
    'RELEASE': 5,
    'GRASP': 6,
    'NONE': 7 # originally 10
}

input_size = 6
hidden_size = 20
num_layers = 1
output_size = len(classes)

model = LSTMClassifier(input_size, hidden_size, num_layers, output_size)
model

LSTMClassifier(
  (lstm): LSTM(6, 20, batch_first=True)
  (fc): Linear(in_features=20, out_features=8, bias=True)
)

In [285]:
num_epochs = 200
learning_rate = 0.0005
# num_epochs = 100
# learning_rate = 0.002

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    for X, y in train_loader:
        y_hat = model(X)
        loss = criterion(y_hat, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

Epoch [1/200], Loss: 1.9522440433502197
Epoch [2/200], Loss: 2.1035680770874023
Epoch [3/200], Loss: 1.9545749425888062
Epoch [4/200], Loss: 2.054863929748535
Epoch [5/200], Loss: 1.8782902956008911
Epoch [6/200], Loss: 2.3192079067230225
Epoch [7/200], Loss: 2.198246717453003
Epoch [8/200], Loss: 2.1222822666168213
Epoch [9/200], Loss: 1.925147294998169
Epoch [10/200], Loss: 2.0253143310546875
Epoch [11/200], Loss: 1.8752200603485107
Epoch [12/200], Loss: 2.298220157623291
Epoch [13/200], Loss: 2.219733476638794
Epoch [14/200], Loss: 2.070958137512207
Epoch [15/200], Loss: 1.9637901782989502
Epoch [16/200], Loss: 1.9575257301330566
Epoch [17/200], Loss: 1.7133293151855469
Epoch [18/200], Loss: 1.8672101497650146
Epoch [19/200], Loss: 2.288347005844116
Epoch [20/200], Loss: 1.8762716054916382
Epoch [21/200], Loss: 2.2073028087615967
Epoch [22/200], Loss: 2.031547784805298
Epoch [23/200], Loss: 1.9186077117919922
Epoch [24/200], Loss: 2.3823721408843994
Epoch [25/200], Loss: 1.6880807876586914
Epoch [26/200], Loss: 1.997882604598999
Epoch [27/200], Loss: 1.7772235870361328
Epoch [28/200], Loss: 1.7691493034362793
Epoch [29/200], Loss: 1.8296722173690796
Epoch [30/200], Loss: 2.4504122734069824
Epoch [31/200], Loss: 1.6872258186340332
Epoch [32/200], Loss: 2.2024102210998535
Epoch [33/200], Loss: 2.026535749435425
Epoch [34/200], Loss: 2.2512385845184326
Epoch [35/200], Loss: 1.628082036972046
Epoch [36/200], Loss: 1.5043127536773682
Epoch [37/200], Loss: 2.395115852355957
Epoch [38/200], Loss: 1.8544317483901978
Epoch [39/200], Loss: 2.0734360218048096
Epoch [40/200], Loss: 1.7597590684890747
Epoch [41/200], Loss: 1.6524417400360107
Epoch [42/200], Loss: 2.472015619277954
Epoch [43/200], Loss: 2.083702325820923
Epoch [44/200], Loss: 1.9556169509887695
Epoch [45/200], Loss: 2.0450308322906494
Epoch [46/200], Loss: 0.31857380270957947
Epoch [47/200], Loss: 0.8529969453811646
Epoch [48/200], Loss: 1.6563687324523926
Epoch [49/200], Loss: 1.7041027545928955
Epoch [50/200], Loss: 2.2214834690093994
Epoch [51/200], Loss: 2.659742832183838
Epoch [52/200], Loss: 2.8851442337036133
Epoch [53/200], Loss: 1.2534730434417725
Epoch [54/200], Loss: 1.7692290544509888
Epoch [55/200], Loss: 2.2112696170806885
Epoch [56/200], Loss: 1.2169811725616455
Epoch [57/200], Loss: 2.3893980979919434
Epoch [58/200], Loss: 2.0324137210845947
Epoch [59/200], Loss: 2.9756829738616943
Epoch [60/200], Loss: 1.893548607826233
Epoch [61/200], Loss: 2.1923305988311768
Epoch [62/200], Loss: 1.743338942527771
Epoch [63/200], Loss: 2.360219717025757
Epoch [64/200], Loss: 1.8891783952713013
Epoch [65/200], Loss: 1.816997766494751
Epoch [66/200], Loss: 1.9586517810821533
Epoch [67/200], Loss: 1.2767658233642578
Epoch [68/200], Loss: 2.183232307434082
Epoch [69/200], Loss: 2.701754570007324
Epoch [70/200], Loss: 1.0607744455337524
Epoch [71/200], Loss: 2.59122633934021
Epoch [72/200], Loss: 2.0115108489990234
Epoch [73/200], Loss: 1.208146095275879
Epoch [74/200], Loss: 2.5782976150512695
Epoch [75/200], Loss: 2.4905307292938232
Epoch [76/200], Loss: 2.2403881549835205
Epoch [77/200], Loss: 0.7627454400062561
Epoch [78/200], Loss: 2.760982036590576
Epoch [79/200], Loss: 1.3467596769332886
Epoch [80/200], Loss: 2.0486485958099365
Epoch [81/200], Loss: 1.8807919025421143
Epoch [82/200], Loss: 2.309422492980957
Epoch [83/200], Loss: 2.1741373538970947
Epoch [84/200], Loss: 1.1967076063156128
Epoch [85/200], Loss: 1.2899694442749023
Epoch [86/200], Loss: 2.392878532409668
Epoch [87/200], Loss: 1.9571834802627563
Epoch [88/200], Loss: 1.5137895345687866
Epoch [89/200], Loss: 2.11140775680542
Epoch [90/200], Loss: 2.09759259223938
Epoch [91/200], Loss: 1.3084630966186523
Epoch [92/200], Loss: 1.8823127746582031
Epoch [93/200], Loss: 0.9445211291313171
Epoch [94/200], Loss: 2.798719882965088
Epoch [95/200], Loss: 0.9838799238204956
Epoch [96/200], Loss: 2.3762149810791016
Epoch [97/200], Loss: 2.6521432399749756
Epoch [98/200], Loss: 1.8470399379730225
Epoch [99/200], Loss: 1.8998777866363525
Epoch [100/200], Loss: 2.0962612628936768
Epoch [101/200], Loss: 2.5410871505737305
Epoch [102/200], Loss: 2.0761585235595703
Epoch [103/200], Loss: 1.6622110605239868
Epoch [104/200], Loss: 2.50942063331604
Epoch [105/200], Loss: 2.2130274772644043
Epoch [106/200], Loss: 1.9717203378677368
Epoch [107/200], Loss: 2.071164608001709
Epoch [108/200], Loss: 1.1461490392684937
Epoch [109/200], Loss: 1.658071756362915
Epoch [110/200], Loss: 1.2757573127746582
Epoch [111/200], Loss: 2.6837024688720703
Epoch [112/200], Loss: 2.3200857639312744
Epoch [113/200], Loss: 2.0104775428771973
Epoch [114/200], Loss: 1.788805603981018
Epoch [115/200], Loss: 0.5684969425201416
Epoch [116/200], Loss: 2.4950737953186035
Epoch [117/200], Loss: 1.8459727764129639
Epoch [118/200], Loss: 1.8551181554794312
Epoch [119/200], Loss: 2.148756504058838
Epoch [120/200], Loss: 2.3570668697357178
Epoch [121/200], Loss: 1.4233616590499878
Epoch [122/200], Loss: 1.5486195087432861
Epoch [123/200], Loss: 2.04992938041687
Epoch [124/200], Loss: 2.130157470703125
Epoch [125/200], Loss: 1.831994652748108
Epoch [126/200], Loss: 2.0057897567749023
Epoch [127/200], Loss: 1.9750792980194092
Epoch [128/200], Loss: 0.9413726329803467
Epoch [129/200], Loss: 1.7904536724090576
Epoch [130/200], Loss: 2.0766196250915527
Epoch [131/200], Loss: 2.2307522296905518
Epoch [132/200], Loss: 0.7883267998695374
Epoch [133/200], Loss: 2.405806541442871
Epoch [134/200], Loss: 2.213158130645752
Epoch [135/200], Loss: 1.8839128017425537
Epoch [136/200], Loss: 1.6219121217727661
Epoch [137/200], Loss: 1.8988063335418701
Epoch [138/200], Loss: 2.0365617275238037
Epoch [139/200], Loss: 1.640805959701538
Epoch [140/200], Loss: 1.5819958448410034
Epoch [141/200], Loss: 2.167422294616699
Epoch [142/200], Loss: 3.6076934337615967
Epoch [143/200], Loss: 1.7296030521392822
Epoch [144/200], Loss: 2.497272491455078
Epoch [145/200], Loss: 1.6558581590652466
Epoch [146/200], Loss: 1.197630763053894
Epoch [147/200], Loss: 2.1418135166168213
Epoch [148/200], Loss: 1.6777071952819824
Epoch [149/200], Loss: 2.1001648902893066
Epoch [150/200], Loss: 1.7952274084091187
Epoch [151/200], Loss: 1.964133620262146
Epoch [152/200], Loss: 0.012430102564394474
Epoch [153/200], Loss: 1.9570585489273071
Epoch [154/200], Loss: 2.2269041538238525
Epoch [155/200], Loss: 1.7341580390930176
Epoch [156/200], Loss: 1.882718801498413
Epoch [157/200], Loss: 1.3674054145812988
Epoch [158/200], Loss: 1.7974827289581299
Epoch [159/200], Loss: 1.8302109241485596
Epoch [160/200], Loss: 0.19527104496955872
Epoch [161/200], Loss: 1.8911794424057007
Epoch [162/200], Loss: 2.2138583660125732
Epoch [163/200], Loss: 1.2105164527893066
Epoch [164/200], Loss: 1.8412309885025024
Epoch [165/200], Loss: 1.8088583946228027
Epoch [166/200], Loss: 1.6956050395965576
Epoch [167/200], Loss: 1.4901896715164185
Epoch [168/200], Loss: 1.4337087869644165
Epoch [169/200], Loss: 1.5304739475250244
Epoch [170/200], Loss: 2.0121781826019287
Epoch [171/200], Loss: 1.3413550853729248
Epoch [172/200], Loss: 1.0711818933486938
Epoch [173/200], Loss: 4.060304164886475
Epoch [174/200], Loss: 1.8463958501815796
Epoch [175/200], Loss: 2.178424119949341
Epoch [176/200], Loss: 0.22029411792755127
Epoch [177/200], Loss: 2.0548171997070312
Epoch [178/200], Loss: 1.8399500846862793
Epoch [179/200], Loss: 0.7152079939842224
Epoch [180/200], Loss: 1.440855622291565
Epoch [181/200], Loss: 2.4033045768737793
Epoch [182/200], Loss: 1.7766735553741455
Epoch [183/200], Loss: 1.8204807043075562
Epoch [184/200], Loss: 2.4308228492736816
Epoch [185/200], Loss: 0.9355889558792114
Epoch [186/200], Loss: 2.5318527221679688
Epoch [187/200], Loss: 1.879717230796814
Epoch [188/200], Loss: 1.6372320652008057
Epoch [189/200], Loss: 2.7527174949645996
Epoch [190/200], Loss: 2.628157138824463
Epoch [191/200], Loss: 1.5464797019958496
Epoch [192/200], Loss: 1.4525079727172852
Epoch [193/200], Loss: 1.2955131530761719
Epoch [194/200], Loss: 1.3869215250015259
Epoch [195/200], Loss: 1.538438081741333
Epoch [196/200], Loss: 1.4641075134277344
Epoch [197/200], Loss: 1.5302590131759644
Epoch [198/200], Loss: 1.1301722526550293
Epoch [199/200], Loss: 1.3873858451843262
Epoch [200/200], Loss: 1.4025602340698242

In [286]:
val_loader = torch.utils.data.DataLoader(val_set,
        batch_size=len(val_set),
        collate_fn=pad_collate,
        shuffle=False
    )

# validation data
val_X, val_y = next(iter(val_loader))
Y_hat = model(val_X)
val_loss = criterion(Y_hat, val_y)
val_err = val_loss.item()

print("Validation loss:", val_err)

RuntimeError: Expected hidden[0] size (1, 40, 20), got [1, 1, 20]

In [287]:
print(X_one.shape)
y_one

torch.Size([100, 6])

tensor([2])

In [288]:
#to_pred = ((X_one - min_val) / (max_val - min_val + 1e-7)).unsqueeze(0)
#to_pred = ((X_one - mean) / std).unsqueeze(0)
to_pred = X_one.unsqueeze(0)
with torch.no_grad():
    predictions = model(to_pred)
    print(predictions)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

tensor([[-0.5117, -0.3923,  0.6039, -0.8837, -0.1896, -0.7421, -0.3947,  0.3287]])
Predicted Labels: tensor([2])

In [289]:
X_another = pl.read_csv("./imu_data/rosbag/data/data_clean/rosbag2_2023_02_10-07_52_42_data.csv").select(
    get_column_combos(imus, dims, readings)
).to_torch(dtype=pl.Float32)

y_another = pl.read_csv("./imu_data/rosbag/data/label/rosbag2_2023_02_10-07_52_42_label.csv").with_columns(
    pl.col('label').replace(10, 7)
).to_torch()[0]

print(X_another.shape)
y_another

torch.Size([100, 6])

tensor([1])

In [290]:
#to_pred = ((X_another - min_val) / (max_val - min_val + 1e-7)).unsqueeze(0)
#to_pred = ((X_another - mean) / std).unsqueeze(0)
to_pred = X_another.unsqueeze(0)
with torch.no_grad():
    predictions = model(to_pred)
    print(predictions)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

tensor([[-0.2569,  0.2516, -0.7057,  0.4298, -0.0773,  0.0618,  0.0426, -0.1248]])
Predicted Labels: tensor([3])

In [291]:
X_another = pl.read_csv("./imu_data/rosbag/data/data_clean/rosbag2_2023_02_27-13_52_46_data.csv").select(
    get_column_combos(imus, dims, readings)
).to_torch(dtype=pl.Float32)

y_another = pl.read_csv("./imu_data/rosbag/data/label/rosbag2_2023_02_27-13_52_46_label.csv").with_columns(
    pl.col('label').replace(10, 7)
).to_torch()[0]

print(X_another.shape)
y_another

torch.Size([184, 6])

tensor([7])

In [292]:
#to_pred = ((X_another - min_val) / (max_val - min_val + 1e-7)).unsqueeze(0)
#to_pred = ((X_another - mean) / std).unsqueeze(0)
to_pred = X_another.unsqueeze(0)
with torch.no_grad():
    predictions = model(to_pred)
    print(predictions)
    predicted_labels = torch.argmax(predictions, dim=1)
    print("Predicted Labels:", predicted_labels)

tensor([[-2.0804,  1.3269, -0.7801, -1.3047,  0.1142, -1.0282, -0.3461,  1.7743]])
Predicted Labels: tensor([7])

In [293]:
X_another.shape

torch.Size([184, 6])

In [294]:
X_one.shape

torch.Size([100, 6])

In [295]:
torch.cat([X_another, X_one]).shape

torch.Size([284, 6])

## ONNX Export

In [296]:
X_one.unsqueeze(0).shape

torch.Size([1, 100, 6])

In [297]:
model_path = "./model/gesture_rec_static.onnx"
input_name = "readings"
output_name = "gesture"
input_tensor = torch.randn(1, 100, 6)#X_one.unsqueeze(0)

model.eval()

torch.onnx.export(
    model,
    input_tensor,
    model_path,
    input_names = [input_name],
    output_names = [output_name],
    # dynamic_shapes=({
    #     0: torch.export.Dim.DYNAMIC,
    #     1: torch.export.Dim.DYNAMIC
    # },),
    # dynamic_shapes={
    #     'x': {
    #         0: "batch_size",
    #         1: "seq_len"
    #     }
    # },
    # dynamic_axes={
    #     input_name: {
    #         0: "batch_size",
    #         1: "seq_len"
    #     },
    #     output_name: {
    #         0: "batch_size",
    #         1: "seq_len" 
    #     }
    # },
    dynamo=False,
    external_data=False
)

/home/kojo/tmp/ipykernel_8341/1916155734.py:8: DeprecationWarning: You are using the legacy TorchScript-based ONNX export. Starting in PyTorch 2.9, the new torch.export-based ONNX exporter has become the default. Learn more about the new export logic: https://docs.pytorch.org/docs/stable/onnx_export.html. For exporting control flow: https://pytorch.org/tutorials/beginner/onnx/export_control_flow_model_to_onnx_tutorial.html
  torch.onnx.export(
/home/kojo/Code/730SemesterProject/exploration/imenv/lib/python3.12/site-packages/torch/onnx/_internal/torchscript_exporter/symbolic_opset9.py:4463: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  return _generic_rnn(

> Need to run onnxsim after this:

```bash
onnxsim ./model/gesture_rec_static.onnx ./model/gesture_rec_static_sim.onnx
```